version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ../filesMap:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      # - mysql
    networks:
      - networkLaravel

  # mysql:
  #   image: mysql:8
  #   container_name: mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "4306:3306"
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   networks:
  #     - laravel

  app:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    working_dir: /var/www/html
    volumes:
      - ../filesMap:/var/www/html
    networks:
      - networkLaravel

networks:
  networkLaravel:
